# NovinHub Webhook Service Configuration

# Server configuration
server:
  port: 8080
  read_timeout: 10
  write_timeout: 10
  host: "0.0.0.0"

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "/var/log/novinhub-webhook/webhook.log"

# Webhook configuration
webhook:
  # Maximum request size in bytes (default: 1MB)
  max_request_size: 1048576
  # Timeout for processing webhook events in seconds
  processing_timeout: 30
  # Enable request logging
  enable_request_logging: true

# Security configuration
security:
  # Enable CORS
  enable_cors: true
  # Allowed origins (empty means all)
  allowed_origins: []
  # Rate limiting (requests per minute per IP)
  rate_limit: 100

# Health check configuration
health:
  # Health check endpoint path
  endpoint: "/health"
  # Health check timeout
  timeout: 5

# SMS configuration
sms:
  # SMS provider (ippanel, kavenegar, melipayamak)
  provider: "ippanel"
  # IPPanel configuration
  ippanel:
    api_key: "OWY1ZTAyMjEtMThmNi00NzRiLWFhOTItZTEwMmFhNDQzZTliZTcwM2EzODg5NzUzNWMwOWE3ZDliYWUyYTExMWZlMzY="
    originator: "+9850002040000000"
    pattern_code: "9i276pvpwvuj40w"
    password_recovery_pattern: "gvqto0pk77stx2t"
  # Enable SMS sending (set to false for testing)
  enabled: true
  # SMS retry configuration
  retry:
    max_attempts: 3
    delay_seconds: 5
  # Pattern management configuration
  patterns:
    enabled: true
    list:
      - "a2xjmxbszf27a7e"  # گروه اول
      - "m3p3jtuu13i4n1o"  # گروه دوم
      - "l05j64348i04cx8"  # گروه سوم
      - "nv4fgs9mczuv6rq"  # گروه چهارم
    current: 0  # Current pattern index (0-based)

# Environment specific settings
environment:
  # Current environment (development, staging, production)
  mode: "development"
  # Enable debug mode
  debug: false
